### ISSUE TITLE
How to remove vertical scrollbar on Firefox

### ISSUE THREAD

**Issue by berj** [scottaohara/accessible_accordions#11]
First of all thank you for giving us this accordion module, it's very generous of you.

I am testing its operation under different browsers.

In Firefox, when the panel opens I see a vertical scroll bar on the right. Once the panel is open, the bar disappears.

With Safari, Goocle Chrome and Opera this bar does not appear.

My question how to remove this bar in Firefox?

Thanks

OS X : 10.14.5
Safari : 12.1.1
Firefox : 67.0
Firefox Developer Edition : 68.0b5 
Google Chrome : 74.0.3729.131
Opera : 60.0.3255.125

![firefox-scrollbar](https://user-images.githubusercontent.com/7210511/58723538-4c569d80-83a8-11e9-92a5-4ae12430a7dc.jpg)

**Comment by scottaohara** [comment]
that's due to the animation of the content expanding from a collapsed height to max-height 100vh and the overflow changing from `hidden` to `auto`.

you could play around with when / if you even need the overflow to change.  maybe updating script to only change to auto after the expansion has run its course.  

In the end though, this is more how Firefox treats content that is expanding in height with an overflow, where the scroll bar is present until it reaches max height and all the content can be revealed without need for a scroll bar.  Outside of what I noted above to work around this, this isn't really an issue but just how firefox behaves.
