### ISSUE TITLE
Is there data attribute which closes it's respective panel??

### ISSUE THREAD

**Issue by sumanita** [scottaohara/accessible_accordions#14]
Hi there, 
This is not an issue. Rather than clicking the heading to close panel. Is there an attribute which we can attached in button which sit inside it's respective panel and closes it. Still new to JS world so any help will be highly appropriated. 

many thanks 
Sumanita

**Comment by scottaohara** [comment]
you could write your own function to allow a button within an exposed panel to close it.  You'd then need to reset the attributes of the persistently exposed button (within the heading) and you'd need to manage keyboard focus, since the button that triggers the close would go away... you'd need to figure out a logical place to return focus (assuming the original button that opened the panel).
